import { Card } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { AlertCircle, Activity, Heart, Droplet, Wind } from "lucide-react";

interface Disease {
  name: string;
  probability: number;
  severity: "low" | "medium" | "high";
}

interface DiseaseResultsProps {
  diseases: Disease[];
  modelAccuracy?: number;
  detectionConfidence?: number;
}

const diseaseIcons: Record<string, any> = {
  pneumonia: Wind,
  effusion: Droplet,
  cardiomegaly: Heart,
  default: Activity,
};

const severityColors = {
  low: "text-low-risk",
  medium: "text-medium-risk",
  high: "text-high-risk",
};

const severityBgColors = {
  low: "bg-low-risk/10",
  medium: "bg-medium-risk/10",
  high: "bg-high-risk/10",
};

export const DiseaseResults = ({ diseases, modelAccuracy = 94.2, detectionConfidence = 0 }: DiseaseResultsProps) => {
  const getSeverityLabel = (severity: string) => {
    return severity.charAt(0).toUpperCase() + severity.slice(1) + " Risk";
  };

  return (
    <Card className="p-6 bg-card border-border shadow-medium">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-primary-light rounded-lg">
            <Activity className="w-5 h-5 text-primary" />
          </div>
          <h2 className="text-xl font-semibold text-foreground">Disease Detection Results</h2>
        </div>
        <div className="flex gap-4">
          <div className="text-right">
            <div className="text-xs text-muted-foreground">Model Accuracy</div>
            <div className="text-lg font-bold text-primary">{modelAccuracy}%</div>
          </div>
          <div className="text-right">
            <div className="text-xs text-muted-foreground">Detection Confidence</div>
            <div className="text-lg font-bold text-accent">{detectionConfidence}%</div>
          </div>
        </div>
      </div>

      <div className="space-y-4">
        {diseases.map((disease, index) => {
          const Icon = diseaseIcons[disease.name.toLowerCase()] || diseaseIcons.default;
          const probabilityPercent = Math.round(disease.probability * 100);

          return (
            <div
              key={index}
              className={`p-4 rounded-xl border border-border ${
                severityBgColors[disease.severity]
              } transition-all hover:shadow-soft`}
            >
              <div className="flex items-start justify-between mb-3">
                <div className="flex items-center gap-3">
                  <div className={`p-2 bg-card rounded-lg ${severityColors[disease.severity]}`}>
                    <Icon className="w-5 h-5" />
                  </div>
                  <div>
                    <h3 className="font-semibold text-foreground capitalize">
                      {disease.name}
                    </h3>
                    <p className={`text-sm ${severityColors[disease.severity]}`}>
                      {getSeverityLabel(disease.severity)}
                    </p>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-2xl font-bold text-foreground">
                    {probabilityPercent}%
                  </div>
                  <p className="text-xs text-muted-foreground">Confidence</p>
                </div>
              </div>

              <div className="space-y-2">
                <div className="flex justify-between text-xs text-muted-foreground">
                  <span>Detection Probability</span>
                  <span>{probabilityPercent}%</span>
                </div>
                <Progress value={probabilityPercent} className="h-2" />
              </div>
            </div>
          );
        })}
      </div>

      <div className="mt-6 p-4 bg-accent-light rounded-xl border border-accent/20">
        <div className="flex gap-3">
          <AlertCircle className="w-5 h-5 text-accent flex-shrink-0 mt-0.5" />
          <div>
            <p className="text-sm font-medium text-accent-foreground mb-1">
              Clinical Notice
            </p>
            <p className="text-xs text-accent-foreground/80">
              These results are generated by AI and should be reviewed by qualified
              radiologists. Not intended for clinical diagnosis.
            </p>
          </div>
        </div>
      </div>
    </Card>
  );
};
